### PR TITLE
Add networking target for users

### PR DESCRIPTION
**Pull request by Timple**
Item numbero # 1 on https://github.com/tue-robotics/tue_robocup/issues/375

### CODE REVIEW

**Comment by Timple** [comment]
Depends on #131 because sudo required for tue-install-cp

**Comment by MatthijsBurgh** [comment]
@Timple please resolve the conflicts

**Comment by MatthijsBurgh** [comment]
Networking target removed from robot-user, is that correct?

**Comment by Timple** [comment]
Click on "VIEW FILE" to see that it has actually moved to the top of the file.

**Pull request merged**
