### PR TITLE
Update gitsu list

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Add Tim Assman, remove Jos Elfring, some spacing fixes.
Not tested at all

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Isn't Jos working at the TU/e occasionally?

**Comment by MatthijsBurgh** [comment]
He is, but is he using our tue-env?

**Comment by LoyVanBeek** [comment]
How can I know? Can you ask him this week? Maybe @reinzor knows?

**Comment by MatthijsBurgh** [comment]
I know het is not in the AMIGO team and not even part of tue-robotics. So he is not able to push anything. So probably also not using our tue-env.

**Comment by reinzor** [comment]
Just leave all 'old' contributors in the list, it is not blocking anything

**Comment by MatthijsBurgh** [comment]
Jos is back in the list.

**Pull request merged**
