### PR TITLE
Use our fork of the ROS diagnostic_updater

### PR DESCRIPTION
**Pull request by LoyVanBeek**
Forked at https://github.com/tue-robotics/diagnostics

Used in https://github.com/tue-robotics/image_recognition/pull/55.

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
@MatthijsBurgh Can you verify that installing this works OK? My ROS env is not a clean tue-env and never has been. Getting this version with that setup was a hassle but it shouldn't be with a normal tue-env.

**Comment by MatthijsBurgh** [comment]
Jep, installing is working. Can be build and rosrun works.

**Comment by Timple** [comment]
I am missing the rationale here.

Why is ours better?

**Comment by LoyVanBeek** [comment]
Fair points! We want to have some diagnostics on the Jetson board, to see if it is up and running.
I was making a diagnostic_updater that publishes a heartbeat but since this was very generic, @reinzor suggested to add this to the standard ROS diagnostics, so I did. 

I forked it and submitted a PR at https://github.com/ros/diagnostics/pull/73

**Pull request merged**
