### PR TITLE
Revert c4c1027e9add13b73ea48dcfd80e78ca269a3ad6, unfork smach

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Because issue is still not resolved.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/console.py in <module>()
     21 
     22 # load state machines
---> 23 import robot_smach_states as state_machine
     24 import robot_smach_states.util.designators as ds
     25 import robot_skills.util.msg_constructors as msgs

/home/amigo/ros/kinetic/system/devel/lib/python2.7/dist-packages/robot_smach_states/__init__.py in <module>()
     33 for __execfile in __execfiles:
     34     with open(__execfile, 'r') as __fh:
---> 35         exec(__fh.read())
     36     del __fh
     37     del __execfile

<string> in <module>()

/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/__init__.py in <module>()
----> 1 from human_interaction import *

/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py in <module>()
      6 import ed_perception.msg
      7 import actionlib
----> 8 from robot_smach_states.state import State
      9 from hmi import TimeoutException
     10 

/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/state.py in <module>()
      4 from robot_smach_states.util.designators import Designator
      5 
----> 6 class State(smach.State):
      7     def __init__(self, *args, **kwargs):
      8         smach.State.__init__(self, outcomes=kwargs['outcomes'])

AttributeError: 'module' object has no attribute 'State'
```

### CODE REVIEW

**Comment by Rayman** [comment]
Then we should fix `robot_smach_states`

**Comment by MatthijsBurgh** [comment]
I don't think it is actually related to our code. Because in iPython your are not able to import anything from smach. Smach is recognized,  but nothing to be imported.

**Comment by Rayman** [comment]
I think its a local issue on your pc. Fresh install:
screenshot from 2017-09-08 10-23-13

**Comment by MatthijsBurgh** [comment]
Do you have your smach folders removed from your workspace? Because workspace is searched first, before looking in installed pkgs.

**Comment by Rayman** [comment]
> I think its a local issue on your pc. **Fresh install:**

**Comment by MatthijsBurgh** [comment]
Oh Fresh install. It was on the right desktop in the lab. I will give it a try at my own laptop.

**Comment by MatthijsBurgh** [comment]
A 'catkin clean' and 'tue-make' solved the problem

**Pull request closed without merging**
