### PR TITLE
Make clear that branch is checked out

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Fix issue of https://github.com/tue-robotics/tue-env/runs/3159129462?check_suite_focus=true#step:4:131

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Later in the CI it keeps waiting to re-open stdin. Same as when not using `< /dev/null`, see https://github.com/tue-robotics/tue-env/runs/3159179565?check_suite_focus=true

The error msg has been there for a longer time. (Last master run https://github.com/tue-robotics/tue-env/runs/3017548690?check_suite_focus=true#step:4:702). So If we fix that issue, we can eliminate the `< /dev/null`.

**Comment by ar13pit** [comment]
Do you know which apt package is requiring the dpkg-preconfigure execution?

**Comment by MatthijsBurgh** [comment]
> Do you know which apt package is requiring the dpkg-preconfigure execution?

Nope

**Comment by MatthijsBurgh** [comment]
This was caused by the circular dependency. See #582 for the real solution.

**Pull request closed without merging**
