### PR TITLE
style: remove blinking style from messages

### PR DESCRIPTION
**Pull request by phvheumen**
Text blink makes text hard to read and slows down the developer workflow.

### CODE REVIEW

**Review by ar13pit — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
I think we can remove the blinking. @ar13pit do you agree?

**Comment by MatthijsBurgh** [comment]
Hahaha

**Comment by ar13pit** [comment]
Was I too fast to merge? :laughing:

**Comment by MatthijsBurgh** [comment]
No, the page wasn't updated when I commented. So I didn't know you merged it.

**Pull request merged**
