### PR TITLE
Switch to kinetic-devel branch to fix eigen3 errors

### PR DESCRIPTION
**Pull request by Timple**
Please not that reviewing this commit effectively means you are reviewing this as well:

https://github.com/tue-robotics/navigation/compare/hydro-devel...kinetic-devel

(Untested)

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Is the current Eigen target sufficient?

**Comment by Timple** [comment]
Yes, but it gives compiler warnings. This modification does not. 

The implementation should be the same so I expect no problems.

**Comment by MatthijsBurgh** [comment]
I will test this tomorrow. So maybe I was a bit too fast here.

**Comment by MatthijsBurgh** [comment]
Still need to be tested.

**Comment by MatthijsBurgh** [comment]
Warnings for dwa_local_planner:

** WARNING ** io features related to openni2 will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** visualization features related to openni3 will be disabled

**Comment by MatthijsBurgh** [comment]
It builds and AMIGO is driving around normally

**Pull request merged**
