### PR TITLE
Update git-clean-local echo statements

### PR DESCRIPTION
**Pull request by ar13pit**
Added colors, spacing and made sure the name of a removed branch is displayed only after a branch has been removed.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Will test this tomorrow

**Comment by MatthijsBurgh** [comment]
When It only found unmerged stale branches, which need the `--force-remove`, it still print the `Removing stale branches:` without any  branches. So either print all branches to be removed there or don't print this if there are only branches which require the `--force-remove`

**Comment by ar13pit** [comment]
@MatthijsBurgh this is done

**Comment by ar13pit** [comment]
> Line 111 also in the IF?

That's fine because the IF block should execute only once while the Line 111 needs to execute multiple times.

**Pull request merged**
