### PR TITLE
revert --no-install-recommends

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by Timple** [comment]
Now I'm curious, what was missing?

**Comment by MatthijsBurgh** [comment]
@timple https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=1735&view=logs&j=29751261-4309-50ec-a2ee-519461d37ff7&t=6401cdf1-8c66-5a78-3d35-914917e4951c&l=270

**Comment by ar13pit** [comment]
This may be an issue pertaining to xenial. Also for python it will probably be better if we considered moving all targets to pip. At times the developers mess up the apt package dependencies and matplotlib is one such thing.

**Comment by MatthijsBurgh** [comment]
@Timple Do you have any alternative solutions? Or other remaining comments? Otherwise I will merge this.

**Comment by Timple** [comment]
I can take a look this evening

**Comment by Timple** [comment]
I can't seem to find what's wrong with the other PR. Some test fails but I cannot figure out why.
If this PR resolves it, it looks like not all used dependencies are listed in the package.xml?

**Pull request merged**
