### PR TITLE
add ppa functionality incl. yaml

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Plus some targets converted.

### CODE REVIEW

**Comment by Timple** [comment]
@MatthijsBurgh what did you think of my comment to enforce starting with ppa instead of leaving it out. This would be consistent with the .git enforcement.

**Comment by MatthijsBurgh** [comment]
This was the easier option, because with ppa: the grep is not working. So the ppa: needs to be removed or the ':' should be converted to '.*'. I don't suggest the last option. But I agree with you that it is better to use ppa:.

**Comment by Timple** [comment]
`grep -h "^deb.*${ppa#ppa:}" /etc/apt/sources.list.d/*`

**Comment by Timple** [comment]
is PPA_ADDED actually cleared between runs?

**Comment by MatthijsBurgh** [comment]
I don't think so. Oops

**Pull request merged**
