### PR TITLE
Github get/create releases

### LINKED ISSUE #379: Add get github releases
Generalize the get releases script from `ros-dashboard` target and add it `tue-functions.bash`.

Add auto release script also.

### PR DESCRIPTION
**Pull request by ar13pit**
Closes #379 

After merge make appropriate changes to `ros-speech_recognition` and `ros-dashboard` targets from tue-robotics/tue-env-targets#30

### CODE REVIEW

**Comment by ar13pit** [comment]
@MatthijsBurgh I have tested this locally for downloading releases from github and it works nicely. It has support for regex for the file name. Test it out for `dashboard` and `hero-display`

1. `hero-display`. Here the latest release is used by default.
    ```bash
    tue-install-get-releases "tue-robotics/hero-display" "^hero.*Image" "."
    ```
1. `dashboard`. Here a release from a specific tag is downloaded
    ```bash
    tue-install-get-releases "tue-robotics/dashboard" "^dashboard(-,+)?-.*.tar.gz" "." "2017-before-rgo"
    ```

The bash function at the moment is just a template function. Checks need to be implemented in it.

**Comment by MatthijsBurgh** [comment]
So how do we get the vX and vX-alpha release?

**Comment by ar13pit** [comment]
The syntax of the command is:
```bash
tue-install-get-releases <REPO_SHORT_URL> <FILENAME> <DOWNLOAD_DIR> [TAG]
```
`FILENAME` supports regular expressions.
`TAG` is optional. If not specified, then the file is downloaded from the latest release.

As vX and vX-alpha are tags, these should be used as the arg 4 of the command.

**Comment by MatthijsBurgh** [comment]
So I could just use this regex, `/^v[0-9]+.[0-9]+.[0-9]+$/` to get a vX.X.X version with x being a number?

**Comment by ar13pit** [comment]
That won't work. I have not added support for regex in tags. At the moment tags need to be exact. So if I understand correctly, the feature that you want is to have regex for filename and tags and then download the most recent file that matches both, if it is not present at the specified output location?

**Comment by MatthijsBurgh** [comment]
Yep, As it would be nice to use this to replace for example `hero-dashboard`, https://github.com/tue-robotics/tue-env-targets/tree/master/hero-dashboard

**Comment by ar13pit** [comment]
Yeah I referred to that itself when I asked the question. This can be extended to meet that requirement. I'll do that tomorrow.

**Pull request merged**
