### PR TITLE
removing amigo3 en sergio3 from multiple functions

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MaxBaeten** [comment]
shall we also remove the -X from the ado and sdo functions? These are never used to open gui's anyway.

**Comment by MatthijsBurgh** [comment]
I think that is a good idea. Do we keep the -X in the terminator configs?

**Comment by MaxBaeten** [comment]
No you can also remove them there.

**Comment by MatthijsBurgh** [comment]
I think it ready to be reviewed/merged

**Comment by Timple** [comment]
Is there a benefit of removing the -X? In the past it was sometimes used
for geany to modify config files on Amigo

Op 17 apr. 2017 6:56 p.m. schreef "Max Baeten" <notifications@github.com>:

**Comment by MatthijsBurgh** [comment]
This can still be done manually

**Pull request merged**
