### PR TITLE
convert pip and system target to lowercase

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
For PIP packages, thi sis OK, but apt is case sensitive. 
E.g. PyQT5 can be installed by pyqt5 not

**Comment by LoyVanBeek** [comment]
Wait a sec. Why is this needed at all, since pip is case insensitive? To compare targets with?

**Comment by MatthijsBurgh** [comment]
Then we have to be sure all the targets are correct. I thought both apt and pip only have lowercase targets.

**Comment by MatthijsBurgh** [comment]
Because both apt and pip are case-sensitive, this will break the installer. So closing this PR.

**Pull request closed without merging**
