### PR TITLE
Set a default data directory

### PR DESCRIPTION
**Pull request by ar13pit**
Directory to save models for image and speech recognition

Before merging correct the paths in targets (tue-robotics/tue-env-targets#29)

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Check https://github.com/tue-robotics/tue-env/blob/master/setup/tue-data.bash. Data has always been stored in `~/ros/data(/private)`, so keep it there.

**Comment by ar13pit** [comment]
I did see that but the keras models are being downloaded to a different location
https://github.com/tue-robotics/tue-env-targets/blob/master/ros-image_recognition_keras/install.bash#L3

So thought of generalizing the location. But the question then is why is the keras model not being placed there?

**Comment by MatthijsBurgh** [comment]
See updated comment, now I will be offline again.

**Comment by ar13pit** [comment]
Closing this PR as this issue needs more discussion and maybe a new design for data management of an env workspace.

**Pull request closed without merging**
