### PR TITLE
Add --debug option to tue-get install

### PR DESCRIPTION
**Pull request by Timple**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Only works when using ' tue-get install --debug PKGS'. So not working with update or when called in different order.

**Comment by Timple** [comment]
Different order works here:

```
amigo@Precision $ tue-get install ros-std_msgs --debug
Updating tue-get... Already up-to-date.

[] INFO: Main loop: installing ros-std_msgs
[] INFO: File /tmp/tue-installer/4896addf30f7e8d7/ros-std_msgs does not exist, going to installation procedure
[ros-std_msgs] INFO: Emptying /home/amigo/ros/kinetic/.env/dependencies/ros-std_msgs
[ros-std_msgs] INFO: Parsing /home/amigo/.tue/installer/targets/ros-std_msgs/install.yaml
[ros-std_msgs] INFO: Running following command: tue-install-ros^system^std-msgs
[ros-std_msgs] INFO: Installing ros package: type = system, source = std-msgs
[ros-std_msgs] INFO: File /tmp/tue-installer/4896addf30f7e8d7/ros does not exist, going to installation procedure
[ros] INFO: Emptying /home/amigo/ros/kinetic/.env/dependencies/ros
[ros] INFO: Sourcing /home/amigo/.tue/installer/targets/ros/install.bash
[ros-std_msgs] INFO: Finished installing ros
[ros-std_msgs] INFO: Adding std-msgs to apt list
[] INFO: Finished installing ros-std_msgs
[~]
amigo@Precision $ 
```

Feature explicitly states: tue-get install.

If we want it at tue-get update as well we can implement this of course

**Comment by Timple** [comment]
Was actually a fair request, implemented tue-get update --debug! :-)

**Comment by MatthijsBurgh** [comment]
```tue-get update --debug```
output:
```
[tue-get] Package '--debug' is not installed.
```

**Pull request merged**
