### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by alberth** [comment]
The comment "#tue-dev plus extra tools" implies for me that the line above "tue-get install tue-dev" isn't actually needed. If that line is required, maybe change it to "# also install extra tools" ?

**Comment by MatthijsBurgh** [comment]
see #159

**Comment by alberth** [comment]
```` shell
tue-get install tue-dev
tue-get install tue-dev-full #tue-dev plus extra tools
````
#159 now really makes that the latter includes the former, as I thought it would be the case.
That makes the first line obsolete, doesn't it?

**Comment by alberth** [comment]
@MatthijsBurgh  close enough, thanks

**Pull request merged**
