### PR TITLE
Fix broken pipe in GitHub Actions

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Fixes https://github.com/tue-robotics/tue-robotics.github.io/runs/1466822946?check_suite_focus=true#step:3:63

### CODE REVIEW

**Comment by ar13pit** [comment]
Why did this error not pop up before in Docker?

**Comment by MatthijsBurgh** [comment]
Because I think this only happens in GH actions

**Comment by ar13pit** [comment]
It is because of `-o pipefail` that has been set in shell setting. Before merging this, I would like to make the appropriate changes in the docker shell to see the same error.

**Comment by MatthijsBurgh** [comment]
I think it happens without the pipefail too.

**Comment by ar13pit** [comment]
It happens because of the options set on the bash shell, which are none in docker. In GH actions, the bash shell is running in strict mode

**Comment by MatthijsBurgh** [comment]
I don't know what strict mode is, but the error happens with running just  `bash {0}`
Error: https://github.com/tue-robotics/tue-robotics.github.io/runs/1466840126?check_suite_focus=true#step:3:306, running  `bash {0}` https://github.com/tue-robotics/tue-robotics.github.io/runs/1466840126?check_suite_focus=true#step:3:9

**Review by ar13pit — APPROVED** [review]
LGTM

**Pull request merged**
