### PR TITLE
[tue-env] Fix user_setup.bash creation in new env

### PR DESCRIPTION
**Pull request by ar13pit**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
What is wrong with the current solution?

**Comment by ar13pit** [comment]
If you initialize a new environment and then do `tue-env config` an error is produced because `user_setup.bash` does not exist and the `edit` does not create a blank file if no file exists
```
[~]
arpit@A3-PC $ tue-env config 
Error: no write permission for file "/home/arpit/test/.env/setup/user_setup.bash"
bash: /home/arpit/test/.env/setup/user_setup.bash: No such file or directory
```

**Comment by MatthijsBurgh** [comment]
Would be better to do this when calling `tue-env config` instead of `tue-env init`

**Comment by ar13pit** [comment]
> Would be better to do this when calling `tue-env config` instead of `tue-env init`

So you want to keep explicit creation of the directory and `user_setup.bash` in bootstrap?
It is anyway required for setting up either `ROS_DISTRO` or `USE_SSH` so why not create it anyway with the initialization of a new environment?

**Comment by jlunenburg** [comment]
@MatthijsBurgh @ar13pit is this urgent?

**Comment by MatthijsBurgh** [comment]
> @MatthijsBurgh @ar13pit is this urgent?

Nope

**Pull request merged**
