### PR TITLE
Fix pip upgrade

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Fixes:
- Version checking was wrong
- user version was updated/installed, while system version is used
- remove unused if check, if statement was the same as if statement of higher level

Before fix: https://travis-ci.org/tue-robotics/telegram_ros/builds/461249039#L2710
After fix: https://travis-ci.org/tue-robotics/telegram_ros/jobs/461252304#L2803

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
No more pip main error in the CI

**Comment by alberth** [comment]
Not failing in one particular case versus correct at all times are very different notions. In particular, the former does not imply the latter.

**Comment by MatthijsBurgh** [comment]
> Not failing in one particular case versus correct at all times are very different notions. In particular, the former does not imply the latter.

True, but it has been failing in all the CI. Everywhere the same script is used. So if one is fixed, probably all are fixed.

**Comment by alberth** [comment]
So you're using this one particular case a lot. As computers tend to be quite good at doing the exact same thing every time, yes, it's likely they all fail or they all work.
However it's still only one case.

While correct implies working, there is no such relation from working to correct. In fact, I have seen working solutions that are just plain wrong.

**Pull request merged**
