### PR TITLE
Ask to continue on error by pulling git

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Error happens when current branch is not on the remote anymore

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
New implementation like tue-get
```
[ros-robot_skills] DEBUG: cd /home/amigo/ros/kinetic/repos/https_//github.com/tue-robotics/tue_robocup.git && git pull --ff-only --prune
Your configuration specifies to merge with the ref 'refs/heads/test_tue_env'
from the remote, but no such ref was fetched.
[ros-robot_skills] DEBUG: 
[ros-robot_skills] Could not update. Continue? [y/n]

```

**Comment by MatthijsBurgh** [comment]
@Rayman please review again

**Comment by Rayman** [comment]
Still the same opinion. You use 13 lines of code for the same thing that happens without the patch.

**Comment by MatthijsBurgh** [comment]
You could provide the option to checkout the master branch. But I don't suggest any other option to resolve the problem at the spot.
The last commit informs you about the error and provides the option to continue or not. So at least some progress.

**Pull request closed without merging**
