### PR TITLE
Change to GitHub

### PR DESCRIPTION
**Pull request by LoyVanBeek**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek ik ben een beetje los gegaan...

**Comment by LoyVanBeek** [comment]
Indeed. Who's a good reviewer for this?

**Comment by LoyVanBeek** [comment]
Or should we split up the PR into
- The functionality to change to github (with the parameters perhaps)
- Timezone stuff
- Refactor (which is handy but clutters this PR)
?

**Comment by MatthijsBurgh** [comment]
I think it too difficult to split it. (You could split the timezone, but that would be silly for that one line in my opinion)
I always ask @Timple for tue-env.

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek Of course you can review my work as well. Also when approving isn't possible.

**Comment by JosjaG** [comment]
When changing the amigo PC's remote back to Github the following happens:
```
[~/ros/kinetic/system/src/tue_robocup] (robocup *$=)
tue-robocup-change-remote robocup origin
[tue_robocup]
no local branch: robocup
```
while the branch certainly exists (as I am on it...)

**Comment by MatthijsBurgh** [comment]
@JosjaG, does it work since the last fixes? @LoyVanBeek Please review one more time?

**Comment by LoyVanBeek** [comment]
If it works for @JosjaG, she can approve and its OK to merger I think

**Comment by LoyVanBeek** [comment]
@Timple can you review? It also works on my laptop

**Comment by Timple** [comment]
Owja, approved... Whups

**Pull request merged**
