### PR TITLE
Removing robot_smach_states install.bash target

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Already in https://github.com/tue-robotics/tue-env/blob/master/installer/scripts/tue-install-impl#L661

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
It also in the tensorflow target, but it needs to stay there,  because bash files are sourced before pip check is run in the installer.

**Comment by MatthijsBurgh** [comment]
Combined pull request with, tue-robotics/tue_robocup#309

**Comment by MatthijsBurgh** [comment]
Please don't merge, I will do a final test before merging.

**Comment by MatthijsBurgh** [comment]
No problems during tue-get update, clean install difficult to test. But no typo's etc.

**Comment by LoyVanBeek** [comment]
Can you check in a docker? Based on tue-env?

**Comment by MatthijsBurgh** [comment]
I am not familiar with docker. Do you have a tutorial of sample?

**Comment by LoyVanBeek** [comment]
I see installation of orocos-kdl and python-orocos-kdl is also removed. Are those installed via another way?

**Comment by MatthijsBurgh** [comment]
These are add to package.xml. See pull request in tue_robocup

**Pull request merged**
