### PR TITLE
Add rosdep support for missing targets

### PR DESCRIPTION
**Pull request by Timple**
To test: simply remove `ros-std_msgs` from your targets. That should normally break stuff I guess :sunglasses:

### CODE REVIEW

**Comment by Timple** [comment]
This cleaned up 80% of our targets and reduces a lot of maintenance effort which is done in the rosdep repository anyway.

**Comment by Timple** [comment]
Ow sorry, accidentally commited the `unset-default` option.

Let me know if you need this splitted.

**Comment by MatthijsBurgh** [comment]
I also gave this a try in the past, https://github.com/tue-robotics/tue-env/pull/385. That version does support pip. I think that solution is a bit more elegant. Please let me know what you think.

**Comment by Timple** [comment]
pip support should be trivial to add here as well.

Your implementation only resolves using rosdep and than tries to install those again using own functions.

This implemenation treats rosdep as any other package manager (apt, pip, snap). So for code consistency I like this better.

**Comment by MatthijsBurgh** [comment]
I don't think that is better way to see rosdep. I see rosdep as a resolving tool. Not as a package manager. What I also like about my solution is that it errors much earlier.

**Comment by Timple** [comment]
That's semantics I guess ;-)

Don't apt/pip/snap also do a lookup-and-install? Just like rosdep?

I'm sure you can also lookup what apt would do and then install with dpkg. But that's just cumbersome.

**Comment by MatthijsBurgh** [comment]
But then you should not parse the rosdep output to forward it to apt. Then you should let rosdep do the call to apt. Then I think it fits in the package manager list

For my the considerations in this decision are:
- What is the fastest?
- I prefer to keep the number of calls to apt-get limited.
- Error as early as possible in a way that we can print the target that causes the error.
- (Keep `tue-get dep` working)

**Comment by Timple** [comment]
> But then you should not parse the rosdep output to forward it to apt. 

Ah, I thought we didn't do that, my bad.

Ahwel. This works. Feel free to modify/improve/reject.

**Pull request closed without merging**
