### PR TITLE
New tensorflow

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Related: tue-robotics/image_recognition#23

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Tried to remove all PIP packages, then run installer. PIP log:
```
yes | pip install --user html5lib==1.0b8 xhtml2pdf graphviz tensorflow 

Collecting html5lib==1.0b8
Collecting xhtml2pdf
Collecting graphviz
  Downloading graphviz-0.8.1-py2.py3-none-any.whl
Collecting tensorflow
  Using cached tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from html5lib==1.0b8)
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from xhtml2pdf)
Collecting reportlab>=2.2 (from xhtml2pdf)
  Using cached reportlab-3.4.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyPdf2 (from xhtml2pdf)
Collecting mock>=2.0.0 (from tensorflow)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.11.0 in /usr/lib/python2.7/dist-packages (from tensorflow)
Collecting backports.weakref>=1.0rc1 (from tensorflow)
  Using cached backports.weakref-1.0.post1-py2.py3-none-any.whl
Requirement already satisfied: wheel in ./.local/lib/python2.7/site-packages (from tensorflow)
Collecting tensorflow-tensorboard<0.2.0,>=0.1.0 (from tensorflow)
  Using cached tensorflow_tensorboard-0.1.8-py2-none-any.whl
Collecting protobuf>=3.3.0 (from tensorflow)
  Using cached protobuf-3.4.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: pip>=1.4.1 in ./.local/lib/python2.7/site-packages (from reportlab>=2.2->xhtml2pdf)
Requirement already satisfied: setuptools>=2.2 in ./.local/lib/python2.7/site-packages (from reportlab>=2.2->xhtml2pdf)
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: pbr>=0.11 in /usr/lib/python2.7/dist-packages (from mock>=2.0.0->tensorflow)
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Installing collected packages: html5lib, reportlab, pyPdf2, xhtml2pdf, graphviz, funcsigs, mock, backports.weakref, bleach, markdown, protobuf, werkzeug, tensorflow-tensorboard, tensorflow
Successfully installed backports.weakref-1.0.post1 bleach-1.5.0 funcsigs-1.0.2 graphviz-0.8.1 html5lib-1.0b8 markdown-2.6.9 mock-2.0.0 protobuf-3.4.0 pyPdf2-1.26.0 reportlab-3.4.0 tensorflow-1.3.0 tensorflow-tensorboard-0.1.8 werkzeug-0.12.2 xhtml2pdf-0.0.6
```
Numpy is already newest version installed by apt-get. Protobuf didn't meet the requirements, so a newer version is installed by PIP.

**Comment by MatthijsBurgh** [comment]
I was able to succesfully train a neural network. Not yet tested on a clean install.

**Comment by MatthijsBurgh** [comment]
@Rayman satisfied? Or did I misunderstand you?

**Comment by Rayman** [comment]
Looks good!

I still don't know what all those `TUE_INSTALL_CURRENT_TARGET` are. Where are they used?

**Comment by MatthijsBurgh** [comment]
These are used in tue-install-debug to show which target is currently active.

**Pull request merged**
